repos:
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      args:
        - --ignore-init-module-imports
        - --in-place
        - --remove-all-unused-imports
        - --remove-duplicate-keys


- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
    - id: isort

- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3.6

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]
