[tool.poetry]
name = "climy"
version = "0.0.1"
description = "CLI Made Easy with Web Interface"
license = "BSD-2-Clause"
authors = ["Ritesh <ritesh@vertexcover.io>"]
readme = "README.rst"
repository = "https://github.com/vertexcover-io/climy"
classifiers = [
    # complete classifier list: http://pypi.python.org/pypi?%3Aaction=list_classifiers
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Operating System :: Unix',
    'Operating System :: POSIX',
    'Operating System :: Microsoft :: Windows',
    'Programming Language :: Python',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: Implementation :: CPython',
    'Programming Language :: Python :: Implementation :: PyPy',
    'Topic :: Utilities',
]
packages = [
    { include = "climy", from = "src" }
]

[tool.poetry.scripts]
climy = 'climy.cli:main'

[tool.poetry.dependencies]
python = "*"
falcon = "^1.4"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
